apiVersion: cluster.redpanda.com/v1alpha2
kind: Console
metadata:
  name: redpanda
spec:
  {{- with .Values.console.nodeSelector }}
  nodeSelector:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 2 | indent 2 }}
  {{- end }}
  {{- with .Values.console.tolerations }}
  tolerations:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 2 }}
  {{- end }}
  replicaCount: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: "100%"
  ingress:
    enabled: true
    className: nginx-internal
    annotations:
      cert-manager.io/cluster-issuer: cloudflare
      external-dns.alpha.kubernetes.io/hostname: redpanda-console-secure.psem.io
      external-dns.alpha.kubernetes.io/ttl: "60"
    hosts:
    - host: redpanda-console-secure.psem.io
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - hosts:
      - redpanda-console-secure.psem.io
      secretName: redpanda-console-secure-ingress-tls
  cluster:
    staticConfiguration:
      kafka:
        brokers:
        - redpanda-0.redpanda.{{ .Release.Namespace }}.svc.cluster.local.:9093
        - redpanda-1.redpanda.{{ .Release.Namespace }}.svc.cluster.local.:9093
        - redpanda-2.redpanda.{{ .Release.Namespace }}.svc.cluster.local.:9093
        sasl:
          mechanism: SCRAM-SHA-512
          username: redpanda-admin
          password:
            secretKeyRef:
              name: redpanda-admin-users
              key: redpanda-admin-password
        tls:
          enabled: true
          caCert:
            secretKeyRef:
              name: redpanda-default-cert
              key: ca.crt
      admin:
        urls:
        - https://redpanda.{{ .Release.Namespace }}.svc.cluster.local.:9644
        tls:
          enabled: true
          caCert:
            secretKeyRef:
              name: redpanda-default-cert
              key: ca.crt
      schemaRegistry:
        urls:
        - https://redpanda-0.redpanda.{{ .Release.Namespace }}.svc.cluster.local.:8081
        - https://redpanda-1.redpanda.{{ .Release.Namespace }}.svc.cluster.local.:8081
        - https://redpanda-2.redpanda.{{ .Release.Namespace }}.svc.cluster.local.:8081
        sasl:
          mechanism: SCRAM-SHA-512
          username: redpanda-admin
          password:
            secretKeyRef:
              name: redpanda-admin-users
              key: redpanda-admin-password
        tls:
          enabled: true
          caCert:
            secretKeyRef:
              name: redpanda-default-cert
              key: ca.crt
