apiVersion: cluster.redpanda.com/v1alpha2
kind: Topic
metadata:
  name: logs
spec:
  additionalConfig:
    retention.ms: "60000"
  cluster:
    staticConfiguration:
      kafka:
        brokers:
        - redpanda-0.redpanda.{{ .Release.Namespace }}.svc.cluster.local.:9093
        - redpanda-1.redpanda.{{ .Release.Namespace }}.svc.cluster.local.:9093
        - redpanda-2.redpanda.{{ .Release.Namespace }}.svc.cluster.local.:9093
        sasl:
          mechanism: SCRAM-SHA-512
          username: redpanda-admin
          password:
            secretKeyRef:
              name: redpanda-admin-users
              key: redpanda-admin-password
        tls:
          enabled: true
          caCert:
            secretKeyRef:
              name: redpanda-default-cert
              key: ca.crt
      admin:
        urls:
        - https://redpanda.{{ .Release.Namespace }}.svc.cluster.local.:9644
        tls:
          enabled: true
          caCert:
            secretKeyRef:
              name: redpanda-default-cert
              key: ca.crt
  partitions: 50
  replicationFactor: 3
